const KEY="expense_calculator_operations_v1", state={rows:[],editingId:null};
const $=id=>document.getElementById(id);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const money=n=>new Intl.NumberFormat("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
const displayDate=v=>{if(!v)return "—";const [y,m,d]=v.split("-");return `${d}.${m}.${y}`};
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function save(){localStorage.setItem(KEY,JSON.stringify(state.rows))}
function load(){try{state.rows=JSON.parse(localStorage.getItem(KEY)||"[]");if(!Array.isArray(state.rows))state.rows=[]}catch{state.rows=[]}}
function totals(rows=state.rows){const income=rows.reduce((s,r)=>s+Number(r.income||0),0),expense=rows.reduce((s,r)=>s+Number(r.expense||0),0);return{income,expense,balance:income-expense}}
function resetForm(){state.editingId=null;$("formTitle").textContent="Новая операция";$("saveButton").textContent="+ Добавить строку";$("cancelEdit").classList.add("hidden");$("incomeDate").value=today();$("expenseDate").value=today();$("income").value="";$("expense").value="";$("recipient").value=""}
function render(){const t=totals();$("totalIncome").textContent=money(t.income);$("totalExpense").textContent=money(t.expense);$("totalBalance").textContent=money(t.balance);$("totalBalance").className=t.balance<0?"red":"green";$("operationCount").textContent=state.rows.length;const body=$("operationsBody");body.innerHTML="";$("emptyState").classList.toggle("hidden",state.rows.length>0);$("tableWrap").classList.toggle("hidden",!state.rows.length);state.rows.forEach(r=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${displayDate(r.incomeDate)}</td><td class="green">+ ${money(r.income)}</td><td>${displayDate(r.expenseDate)}</td><td class="red">− ${money(r.expense)}</td><td>${esc(r.recipient)}</td><td class="${r.difference<0?"red":"green"}">${r.difference>=0?"+":""}${money(r.difference)}</td><td><div class="row-actions"><button class="action edit" data-a="edit" data-id="${r.id}">Изменить</button><button class="action delete" data-a="delete" data-id="${r.id}">Удалить</button></div></td>`;body.appendChild(tr)})}
function submit(e){e.preventDefault();const income=Number($("income").value)||0,expense=Number($("expense").value)||0;if(income<=0&&expense<=0){alert("Введите сумму поступления или расхода.");return}const row={id:state.editingId||crypto.randomUUID(),incomeDate:$("incomeDate").value,income,expenseDate:$("expenseDate").value,expense,recipient:$("recipient").value.trim()||"—",difference:income-expense};state.rows=state.editingId?state.rows.map(r=>r.id===state.editingId?row:r):[row,...state.rows];save();render();resetForm()}
function edit(id){const r=state.rows.find(x=>x.id===id);if(!r)return;state.editingId=id;$("formTitle").textContent="Редактирование операции";$("saveButton").textContent="Сохранить изменения";$("cancelEdit").classList.remove("hidden");$("incomeDate").value=r.incomeDate;$("income").value=r.income||"";$("expenseDate").value=r.expenseDate;$("expense").value=r.expense||"";$("recipient").value=r.recipient==="—"?"":r.recipient;scrollTo({top:0,behavior:"smooth"})}
function reportRows(){const f=$("reportFrom").value,t=$("reportTo").value;return state.rows.filter(r=>{const ok=d=>d&&(!f||d>=f)&&(!t||d<=t);return ok(r.incomeDate)||ok(r.expenseDate)})}
function preview(){const t=totals(reportRows());$("reportCount").textContent=reportRows().length;$("reportIncome").textContent=money(t.income);$("reportExpense").textContent=money(t.expense);$("reportBalance").textContent=money(t.balance)}
function printReport(){const rows=reportRows(),t=totals(rows),f=$("reportFrom").value,to=$("reportTo").value,period=f||to?`Период: ${f?displayDate(f):"—"} — ${to?displayDate(to):"—"}`:"Все операции";const trs=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${displayDate(r.incomeDate)}</td><td>${money(r.income)}</td><td>${displayDate(r.expenseDate)}</td><td>${money(r.expense)}</td><td>${esc(r.recipient)}</td><td>${money(r.difference)}</td></tr>`).join("");const w=open("","_blank");if(!w){alert("Разрешите всплывающие окна для этого сайта.");return}w.document.write(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Отчёт</title><style>body{font-family:Arial;padding:28px;color:#111827}h1{margin-bottom:4px}.period{color:#6b7280;margin-bottom:22px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:22px}.card{border:1px solid #ddd;border-radius:8px;padding:12px}.card span{display:block;color:#6b7280;font-size:12px}.card strong{font-size:18px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #ddd;padding:7px;text-align:left}th{background:#f3f4f6}</style></head><body><h1>Отчёт: расходы и доходы</h1><div class="period">${period}</div><div class="cards"><div class="card"><span>Доход</span><strong>${money(t.income)}</strong></div><div class="card"><span>Расход</span><strong>${money(t.expense)}</strong></div><div class="card"><span>Разница</span><strong>${money(t.balance)}</strong></div></div><table><thead><tr><th>№</th><th>Дата дохода</th><th>Доход</th><th>Дата расхода</th><th>Расход</th><th>Кому выдано</th><th>Разница</th></tr></thead><tbody>${trs||"<tr><td colspan='7'>Нет операций</td></tr>"}</tbody></table><script>onload=()=>setTimeout(()=>print(),250)</script></body></html>`);w.document.close()}
$("operationForm").addEventListener("submit",submit);$("cancelEdit").addEventListener("click",resetForm);$("operationsBody").addEventListener("click",e=>{const b=e.target.closest("[data-a]");if(!b)return;const id=b.dataset.id;if(b.dataset.a==="edit")edit(id);else{if(confirm("Удалить операцию?")){state.rows=state.rows.filter(r=>r.id!==id);save();render()}}});$("clearAll").addEventListener("click",()=>{if(state.rows.length&&confirm("Удалить все операции?")){state.rows=[];save();render();resetForm()}});$("reportButton").addEventListener("click",()=>{$("reportFrom").value="";$("reportTo").value="";preview();$("reportModal").classList.remove("hidden")});$("closeReport").addEventListener("click",()=>$("reportModal").classList.add("hidden"));$("closeReport2").addEventListener("click",()=>$("reportModal").classList.add("hidden"));$("reportFrom").addEventListener("change",preview);$("reportTo").addEventListener("change",preview);$("printReport").addEventListener("click",printReport);load();resetForm();render();