const SPREADSHEET_ID='ВСТАВЬТЕ_ID_ТАБЛИЦЫ';const SHEET_NAME='Операции';const APP_KEY='ПРИДУМАЙТЕ_ДЛИННЫЙ_СЕКРЕТНЫЙ_КЛЮЧ';
function setup(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);let sh=ss.getSheetByName(SHEET_NAME);if(!sh)sh=ss.insertSheet(SHEET_NAME);if(sh.getLastColumn()>=7&&String(sh.getRange(1,7).getValue())==='updatedAt')sh.deleteColumn(7);if(sh.getLastRow()===0)sh.appendRow(['id','incomeDate','incomeAmount','expenseDate','expenseAmount','recipient']);formatSheet(sh)}
function formatSheet(sh){sh.getRange(1,1,1,6).setFontWeight('bold');sh.getRange(1,1,sh.getMaxRows(),2).setBackground('#e7f7e7');sh.getRange(1,4,sh.getMaxRows(),3).setBackground('#fdeaea');sh.setFrozenRows(1)}
function doPost(e){try{const p=JSON.parse(e.postData.contents||'{}');if(p.key!==APP_KEY)return out({ok:false,error:'Неверный ключ'});setup();if(p.action==='list')return out({ok:true,rows:list()});if(p.action==='add'){add(p.row);return out({ok:true})}if(p.action==='update'){update(p.row);return out({ok:true})}if(p.action==='delete'){remove(p.id);return out({ok:true})}if(p.action==='clear'){clear();return out({ok:true})}return out({ok:false,error:'Неизвестное действие'})}catch(err){return out({ok:false,error:String(err)})}}
function list(){const v=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(SHEET_NAME).getDataRange().getValues();return v.slice(1).filter(r=>r[0]).map(r=>({id:String(r[0]),incomeDate:String(r[1]||'-'),incomeAmount:Number(r[2])||0,expenseDate:String(r[3]||'-'),expenseAmount:Number(r[4])||0,recipient:String(r[5]||'-')}))}
function add(x){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(SHEET_NAME);sh.appendRow([x.id||Utilities.getUuid(),x.incomeDate||'-',Number(x.incomeAmount)||0,x.expenseDate||'-',Number(x.expenseAmount)||0,x.recipient||'-']);formatSheet(sh)}
function update(x){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(SHEET_NAME),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(x.id)){sh.getRange(i+1,1,1,6).setValues([[x.id,x.incomeDate||'-',Number(x.incomeAmount)||0,x.expenseDate||'-',Number(x.expenseAmount)||0,x.recipient||'-']]);formatSheet(sh);return}throw Error('Запись не найдена')}
function remove(id){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(SHEET_NAME),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(id)){sh.deleteRow(i+1);formatSheet(sh);return}throw Error('Запись не найдена')}
function clear(){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(SHEET_NAME);if(sh.getLastRow()>1)sh.deleteRows(2,sh.getLastRow()-1);formatSheet(sh)}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}